### ISSUE TITLE
no .npz file

### ISSUE THREAD

**Issue by lichaoaaron** [Amanda-Zheng/Auto-HeG#1]
Hi,  I got this error 
"No such file or directory: './splits_search/texas/texas_split_0.4_0.4_0.2.npz' "

The .npz files are not provided.

**Comment by Amanda-Zheng** [comment]
Hi, I have uploaded the splits_search folder in script, thanks for your question and attention on our work.

**Comment by lichaoaaron** [comment]
Thank you!
