### ISSUE TITLE
no self.set_arch_parameters

### ISSUE THREAD

**Issue by lichaoaaron** [Amanda-Zheng/Auto-HeG#2]
Hi, I got an error 'Network' object has no attribute 'set_arch_parameters'.

The function set_arch_parameters is not defined.

**Comment by Amanda-Zheng** [comment]
Could I know which .py you ran for this error?

**Comment by lichaoaaron** [comment]
I run main_search.py, and the error is in model_search.py
def set_state_dict (self. checkpoint): 

This error is because self.set_arch_parameters is not defined in the class Network

**Comment by lichaoaaron** [comment]
Hi, you have provided the folder split_serach. However, the folder splits_geom is not provided.

I got an error 'No such file or directory: '../splits_geom/texas_split_0.6_0.2_1.npz' in train4tune.py

**Comment by Amanda-Zheng** [comment]
I have uploaded the splits_geom and also updated the 'model_search.py' with added self.set_arch_parameters. You could try later.

**Comment by lichaoaaron** [comment]
Now everything is OK. Thank you!

**Comment by Amanda-Zheng** [comment]
Thanks for your attention to our work.
